name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]  # Fixed: was "0 0 * **"
  workflow_dispatch:
  push: {branches: ["main", "master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      # Header (basic info)
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header
          output_action: commit
          filename: metrics-header.svg
      # Calendar (weekly commits)
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          output_action: commit
          filename: metrics-isocalendar.svg
      # Languages used
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.indepth.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
            plugin_languages_indepth: yes
            plugin_languages_details: lines, bytes-size
            plugin_languages_limit: 4
            plugin_languages_analysis_timeout: 15
      # Achievements
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: compact
          output_action: commit
          filename: metrics-achievements.svg
      # Developer habits
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_trim: false
          output_action: commit
          filename: metrics-habits.svg
      # Code lines added/deleted
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.lines.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: repositories
          plugin_lines: yes
          plugin_lines_delay: 30
